### ISSUE TITLE
[Suggestion] Run Java code on click event

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/Issues-ItemsAdder#201]
**Is your feature request related to a problem? Please describe.**
I'm developing plugin for a server and I would like to easily make link between it and ItemsAdder without creating a command to run for each functionality. I would like to run direct java code from click events.

**Describe the solution you'd like**
Something like that : 
```yml
events:
  right_click:
    java: 'Bukkit.getPlayer("Golshr").sendTitle("xyzzy", "");'
```
We can also imagine having already defined local variables to do things like : 
```yml
events:
  right_click:
    java: 'player.sendMessage("this is a " + targetedBlock.getType().toString());'
```
**Describe alternatives you've considered**
I made a HashMap<Block,Runnable> and ~~it looks like shit~~ it's not really efficient and doesn't exactly do the thing I want
